channel_sources:
  - nsls2forge,defaults
channel_targets:
  - nsls2forge main
cdt_name:
  - cos6
c_compiler_version:    # [linux]
  - 7.3                # [linux]
cxx_compiler_version:  # [linux]
  - 7.3                # [linux]
fortran_compiler_version:  # [unix]
  - 7                      # [linux]
  - 4                      # [osx and x86_64]
numpy:
  - 1.16
  - 1.16
  - 1.16
python:
  - 3.7
  - 3.8
  - 3.9
python_impl:
  - cpython
  - cpython
  - cpython
